all: compile compile2 compile3

compile:main.cpp
	g++ main.cpp -o output1
compile2:secondmain.cpp
	g++ -pthread secondmain.cpp -o output2 
compile3:thirdmain.cpp
	g++ -pthread thirdmain.cpp -o output3

